# Generated by Django 3.2.16 on 2023-05-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('zip_code_pick_up', models.CharField(default=0, max_length=10)),
                ('zip_code_delivery', models.CharField(max_length=10)),
                ('city_pick_up', models.CharField(blank=True, max_length=255, null=True)),
                ('state_pick_up', models.CharField(blank=True, max_length=255, null=True)),
                ('lat_pick_up', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng_pick_up', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pick_up', models.BooleanField(default=False)),
                ('city_delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('state_delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('lat_delivery', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng_delivery', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
